//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVALSOKOLOV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public System.DateTime Register { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
        public Nullable<int> Programmer { get; set; }
        public int Sender { get; set; }
    
        public virtual Programmers Programmers { get; set; }
        public virtual Senders Senders { get; set; }
    }
}
